### ISSUE TITLE
JSON format compatibility?

### ISSUE THREAD

**Issue by mscdex** [chrispalazzolo/3dstojs#1]
Is the output from this script compatible with say three.js or similar? If not, I think having that kind of compatibility would be very beneficial.

**Comment by chrispalazzolo** [comment]
The output from this parser is not directly compatible with Three.js or any other 3d lib.  I purposely kept the output agnostic and close to the 3ds file format as possible for those who might be creating their own 3d lib.  I had the idea of it producing an output that is compatible with Three.js via an option flag, but never got around to implementing it.
